[[resources-user]]
== User
A `User` represents a human user of the system, usually in front of an UI who interacts with the system. `User` representations can be
created, modified and retrieved. An `User` is also allowed to authenticate against an UAA endpoint.

[[user-index]]
=== User Index
An overview of all possible operations on `Users` can be found on the `User` index page that is retrieved with a `GET` request:
include::{generated}/users-index/http-request.adoc[]

And the server responds with a `HAL+JSON` representation to further operations:
include::{generated}/users-index/http-response.adoc[]

[[user-create]]
=== Create an User
To create a new `User` instance, a `POST` request must be send to the server with the mandatory fields of the `User` resource in the request
body.
include::{generated}/user-create/http-request.adoc[]
include::{generated}/user-create/request-fields.adoc[]

If the `User` has been created successfully, the server returns the URI to the created resource in the `Location` header:
include::{generated}/user-create/http-response.adoc[]

If an `User` with the same name already exists the server returns an error:
include::{generated}/user-create-exists/http-response.adoc[]

[[user-findall]]
=== Find all Users
To find and retrieve an array of all existing `Users` a client may call a `GET` request:
include::{generated}/user-findAll/http-request.adoc[]

and returns either an array of `Users`...
include::{generated}/user-findAll/http-response.adoc[]

or an empty array, but always with a `200-OK`.
include::{generated}/user-findNone/http-response.adoc[]

[[user-findbypkey]]
=== Find an User by persistent key
A newly created `User` can be retrieved by following the URI in the `Location` header of the response. This URI points to the created
resource:
include::{generated}/user-findByPkey/http-request.adoc[]

If the resource exists the server responds with a `200-OK` and the `User` representation in the response body.
include::{generated}/user-findByPkey/http-response.adoc[]

[[user-save]]
=== Modify an existing User
An existing `User` instance can be modified by sending a `PUT` request with the `User` representation as request body.
include::{generated}/user-save/http-request.adoc[]

If the server has correctly updated the `User` the response is a:
include::{generated}/user-save/http-response.adoc[]

[[user-changepassword]]
=== Change the Users password
Send a `POST` request to the `Users` password attribute to set or change the password of an that `User`.
include::{generated}/user-change-password/http-request.adoc[]

If the server has successfully set the password the response looks like:
include::{generated}/user-change-password/http-response.adoc[]

[[user-saveimage]]
=== Update the image of an existing User
To set the image of an existing `User` a client needs to send a `PATCH` request along the image in the `UserDetails`.
include::{generated}/user-saveimage/http-request.adoc[]

If the server has correctly updated the `Users` image the response looks like:
include::{generated}/user-saveimage/http-response.adoc[]

[[user-delete]]
=== Delete an User
To finally delete all `User` data a `DELETE` request with the persistent key of the `User` is required:
include::{generated}/user-delete/http-request.adoc[]

If the `User` is not assigned somewhere else (in `Roles`) and it has been deleted successfully the server responds:
include::{generated}/user-delete/http-response.adoc[]
