[[resources-user]]
== User
A `User` represents a human user of the system, usually in front of an UI who interacts with the system. `User` representations can be
created, modified and retrieved. An `User` is also allowed to authenticate against an UAA endpoint.

=== User Index
An overview of all possible operations on `Users` can be found on the `User` index page that is retrieved with a `GET` request:

include::{generated}/users-index/http-request.adoc[]

And the server responds with a `HAL+JSON` representation to further operations:

include::{generated}/users-index/http-response.adoc[]

=== Create an User
To create a new `User` instance a `POST` request must be send to the server with the mandatory fields of the `User` in the request body

include::{generated}/user-create/http-request.adoc[]
include::{generated}/user-create/request-fields.adoc[]

If the `User` has been created successfully, the server returns the URI to the created resource in the `Location` header:

include::{generated}/user-create/http-response.adoc[]

=== Find an User by persistent key
A newly created `User` can be retrieved by following the URI in the `Location` header of the response. This URI points to the created
resource:

include::{generated}/user-findByPkey/http-request.adoc[]

If the resource exists the server responds with a `200-OK` and the `User` representation in the response body.

include::{generated}/user-findByPkey/http-response.adoc[]

=== Get the User Details (OAuth2 UserDetails)
An endpoint exists to get the details of the current logged-in `User` from. An OAuth2 Access Token must be provided as Bearer token in order
to access the endpoint.

include::{generated}/oauth-findUserInfo/http-request.adoc[]

If the access token is valid and the server granted access to the resource, a JSON object with the user details is returned.

include::{generated}/oauth-findUserInfo/http-response.adoc[]

include::{generated}/oauth-findUserInfo/response-fields.adoc[]

=== Delete an User
To finally delete all `User` data a `DELETE` request to the persistent key of the `User` is required:

include::{generated}/user-delete/http-request.adoc[]

If the `User` is not assigned somewhere else (in `Roles`) and it has been deleted successfully the server responds:

include::{generated}/user-delete/http-response.adoc[]
