[[resources-role]]
== Role
A `Role` represents...

=== Role Index
An overview of all possible operations on `Roles` can be found on the `Role` index page that is retrieved with a `GET` request:

include::{generated}/roles-index/http-request.adoc[]

And the server responds with a `HAL+JSON` representation to further operations:

include::{generated}/roles-index/http-response.adoc[]

=== Find all Roles
To find and retrieve an array of all existing `Roles` a role may call a `GET` request:

include::{generated}/role-findAll/http-request.adoc[]

and returns either an array of `Roles` or an empty array, but always a `200-OK`.

include::{generated}/role-findAll/http-response.adoc[]

=== Modify an existing Role
An existing `Role` instance can be modified by sending a `PUT` request with the `Role` representation as request body. At least the name of
the `Role`, as an identifying attribute must be set.

include::{generated}/role-save/http-request.adoc[]

include::{generated}/role-save/request-fields.adoc[]

If the server has correctly updated the `Role` the response contains the updated representation:

include::{generated}/role-save/http-response.adoc[]

If the name of the `Role` to update is missing, the server responds with an error:

include::{generated}/role-save-noname/http-response.adoc[]

=== Delete a Role
To finally delete all `Role` data, a `DELETE` request with the persistent key of the `Role` is required:

include::{generated}/role-delete/http-request.adoc[]

If the `Role` has been deleted successfully the server responds:

include::{generated}/role-delete/http-response.adoc[]
