[[resources-role]]
== Role
An `User` could be assigned to multiple `Roles` and act on behalf of a `Role`. Additionally a `Role` assigns `Grants` to all the `Users`
that are assigned to this `Role`. By doing so, a `Role` is also a group of `Grants` that can be assigned to multiple `Users`.

=== Role Index
An overview of all possible operations on `Roles` can be found on the `Role` index page that is retrieved with a `GET` request:

include::{generated}/roles-index/http-request.adoc[]

And the server responds with a `HAL+JSON` representation to further operations:

include::{generated}/roles-index/http-response.adoc[]

=== Create a Role
To create a new `Role` instance, a `POST` request must be send to the server with the mandatory fields of the `Role` in the request body.

include::{generated}/role-create/http-request.adoc[]
include::{generated}/role-create/request-fields.adoc[]

If the `Role` has been created successfully, the server returns the URI to the created resource in the `Location` header:

include::{generated}/role-create/http-response.adoc[]

If a `Role` with the same name already exists the server returns an error:

include::{generated}/role-create-exists/http-response.adoc[]

=== Find all Roles
To find and retrieve an array of all existing `Roles` a role may call a `GET` request:

include::{generated}/role-findAll/http-request.adoc[]

and returns either an array of `Roles` or an empty array, but always a `200-OK`.

include::{generated}/role-findAll/http-response.adoc[]

=== Modify an existing Role
An existing `Role` instance can be modified by sending a `PUT` request with the `Role` representation as request body. At least the name of
the `Role`, as an identifying attribute must be set.

include::{generated}/role-save/http-request.adoc[]

include::{generated}/role-save/request-fields.adoc[]

If the server has correctly updated the `Role` the response contains the updated representation:

include::{generated}/role-save/http-response.adoc[]

If the name of the `Role` to update is missing, the server responds with an error:

include::{generated}/role-save-noname/http-response.adoc[]

=== Delete a Role
To finally delete all `Role` data, a `DELETE` request with the persistent key of the `Role` is required:

include::{generated}/role-delete/http-request.adoc[]

If the `Role` has been deleted successfully the server responds:

include::{generated}/role-delete/http-response.adoc[]

=== Assign an User to a Role
`Users` can be assigned to one or more `Roles`. To assign an existing `User` to an existing `Role` the client must send a `POST` request
to the primary `Role` resource:

include::{generated}/role-assign-user/http-request.adoc[]

If the `User` has been assigned successfully, the server responds with `200-OK`:

include::{generated}/role-assign-user/http-response.adoc[]

If the `User` or the `Role` do not exist the server responds with an error:

include::{generated}/role-assign-unknown-user/http-response.adoc[]

=== Unassign an User from a Role
Already assigned `Users` can be unassigned from a `Role`. Therefore the client sends a `DELETE` request on the secondary `User` resource of
the primary `Role` resource. Note: This will not delete the `User` but delete the assignment between the `Role` and the `User`.

include::{generated}/role-unassign-user/http-request.adoc[]

If the `User` has been unassigned successfully, the server responds with `200-OK`:

include::{generated}/role-unassign-user/http-response.adoc[]

If the `User` or the `Role` do not exist the server responds with an error:

include::{generated}/role-unassign-unknown-role/http-response.adoc[]
