[[resources-grant]]
== Grant
A `Grant` represents a permission to perform an action. A `Grant` can be assigned to a `Role` and is always tied to some kind of action that
can be taken. It has a unique business key, that is used in API or UI to protect against unauthorized access.

[[grant-index]]
=== Grant Index
An overview of all possible operations on `Grants` can be found on the `Grant` index page that is retrieved with a `GET` request:
include::{generated}/grants-index/http-request.adoc[]

And the server responds with a `HAL+JSON` representation to further operations:
include::{generated}/grants-index/http-response.adoc[]

[[grant-create]]
=== Create a Grant
To create a new `Grant` instance, a `POST` request must be send to the server with the mandatory fields of the `Grant` resource in the
request body.
include::{generated}/grant-create/http-request.adoc[]

Not named properties are optional to pass.
include::{generated}/grant-create/request-fields.adoc[]

If the `Grant` has been created successfully, the server returns the URI to the created resource in the `Location` header:
include::{generated}/grant-create/http-response.adoc[]

If a `Grant` with the same name already exists the server returns an error:
include::{generated}/grant-create-exists/http-response.adoc[]

[[grant-findall]]
=== Find all Grants
To retrieve all existing `Grants` from the server, a client simply needs to do a `GET` request to the `Grants` resource.
include::{generated}/grant-findall/http-request.adoc[]

The server responds with a list representation of all `Grants` or an empty list:
include::{generated}/grant-findall/http-response.adoc[]

[[grant-findbypkey]]
=== Find a Grant by persistent key
Each `Grant` has an unique ID the _pKey_ or _persistent identifier_. To find and return a `Grant` by `pKey` a client must send a `GET`
request to the `Grants` resource:
include::{generated}/grant-findbypkey/http-request.adoc[]
include::{generated}/grant-findbypkey/http-response.adoc[]
include::{generated}/grant-findbypkey/response-fields.adoc[]

[[grant-findallforuser]]
=== Find all Grants of a User
To retrieve all existing `Grants` from assigned to a `User`, a client simply needs to do a `GET` request to the `Grants` resource and pass
the users identity within the `X-Identity` http header.
include::{generated}/grant-findallforuser/http-request.adoc[]

The server responds with a list representation of all `Grants`:
include::{generated}/grant-findallforuser/http-response.adoc[]

or a HTTP `204-NO CONTENT` response if no `Grants` are assigned to the `User`:
include::{generated}/grant-findallforuser-empty/http-response.adoc[]

or a HTTP `404-NOT FOUND` response if the `User` does not exist:
include::{generated}/grant-findallforuser-404/http-response.adoc[]
