[[resources-client]]
== Client
A `Client` represents a OAuth2 respectively OpenID Connect client that acts as a resource consumer and tries to access a protected resource
server. Mostly a `Client` is an application or a software service.

=== Client Index
An overview of all possible operations on `Clients` can be found on the `Client` index page that is retrieved with a `GET` request:
include::{generated}/clients-index/http-request.adoc[]

And the server responds with a `HAL+JSON` representation to further operations:
include::{generated}/clients-index/http-response.adoc[]

=== Create a Client
To create a new `Client` instance, a `POST` request must be send to the server with the mandatory fields of the `Client` in the request body
include::{generated}/client-create/http-request.adoc[]
include::{generated}/client-create/request-fields.adoc[]

If the `Client` has been created successfully, the server returns the newly created resource in the response body:
include::{generated}/client-create/http-response.adoc[]

=== Find all Clients
To find and retrieve an array of all existing `Clients` a client may call a `GET` request:
include::{generated}/client-findAll/http-request.adoc[]

and returns either an array of `Clients` or an empty array, but always a `200-OK`.
include::{generated}/client-findAll/http-response.adoc[]

=== Find a Client by persistent key
To find and retrieve a existing `Client` by its persistent key a `GET` request with the `pKey` as path variable must be sent to the server:
include::{generated}/client-findByPKey/http-request.adoc[]

If the `Client` instance with this `pKey` exists the server sends back the response.
include::{generated}/client-findByPKey/http-response.adoc[]

If no `Client` instance exists the server responds with:
include::{generated}/client-findByPKey-404/http-response.adoc[]

=== Modify an existing Client
An existing `Client` instance can be modified by sending a `PUT` request with the `Client` representation as request body.
include::{generated}/client-save/http-request.adoc[]

If the server has correctly updated the `Client` the response contains the updated representation:
include::{generated}/client-save/http-response.adoc[]

=== Delete a Client
To finally delete all `Client` data, a `DELETE` request with the persistent key of the `Client` is required:
include::{generated}/client-delete/http-request.adoc[]

If the `Client` has been deleted successfully the server responds:
include::{generated}/client-delete/http-response.adoc[]
