language: java

jdk:
  - openjdk11

env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

cache:
  directories:
    - .autoconf
    - $TRAVIS_HOME/.m2

services:
  - docker
  - rabbitmq
  - postgresql

before_install:
  - "sudo apt-get install graphviz"

install: true

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER \"KARL\" WITH PASSWORD 'KARL';" -U postgres

addons:
  sonarcloud:
    organization: "openwms-github"
  postgresql: '9.6'

script:
  - if [[ ( "$TRAVIS_BRANCH" != "master" ) ]]; then mvn package -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -U -B $MAVEN_OPTS; fi
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn clean package sonar:sonar -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Psonar -B $MAVEN_OPTS; fi
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn site scm-publish:publish-scm -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST,TESTPG -Denforcer.skip=true -Dscmpublish.pubScmUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.core.uaa.git -DdeveloperConnectionUrl=scm:git:https://${PUSHKEY}@github.com/openwms/org.openwms.core.uaa.git -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Pschemagen -B $MAVEN_OPTS; fi
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn clean package -Denforcer.skip=true -DskipTests=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Prelease,gpg -B $MAVEN_OPTS; fi

after_success:
  - docker build -t openwms/org.openwms.core.uaa:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
