eureka:
  client:
    healthcheck:
      enabled: true

owms:
  security:
    encoder:
      bcrypt:
        strength: 4
    provider:
      issuerUrl: http://localhost:8110
    successUrl: "/"
    system:
      username: openwms
      password: openwms