[[section-introduction-and-goals]]
== Introduction and Goals
The OpenWMS.org UAA (User Authentication & Administration) Service is built to fulfill two different requirements regarding the handling of
`Users` of the system.

* First the service is capable to act as http://openid.net/connect[OpenID Connect] authentication endpoint and can authenticate users
against a persistent database.

* The second part deals with the administration of `Users` like creating new `Users`, updating properties of existing ones or deleting them.
Most application permissions were not directly assigned to `Users` explicitly, but to `Roles` instead. `Users` are assigned to `Roles` and
application permissions were granted to particular `Roles`. Administration of `Roles` and permissions is especially required for a UI
application.

=== Functional Requirements

=== Quality Goals

[cols="1,2,3,4,5" options="header"]
|===
| **Priority** | **Characteristic** | **Scenario** | **Activity** | **Risk**
| HIGH | Availability | As a central point for authentication the service must inherit the availability of the highest available service in the installation | Service must be capable to run in failover mode in at least 2 different environments | --
|===
