name: 'master_build'
on:
  repository_dispatch:
  push:
    branches: [ master ]

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build & Test Microservice
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "interface21-snapshots",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_PASSWORD }}"
            },
            {
              "id": "interface21-releases",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_PASSWORD }}"
            }]
      - name: Build
        run: >
          ./mvnw verify
          -DsurefireArgs=-Dspring.profiles.active=TEST
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -U -B $MAVEN_OPTS
      - name: Build Image
        run: ./scripts/docker_build
      - name: Upload Image
        run: ./scripts/docker_push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build-Enterprise
        run: >
          ./mvnw clean verify
          -DsurefireArgs=-Dspring.profiles.active=TEST
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -Penterprise -B $MAVEN_OPTS
      - name: Build Enterprise Image
        run: ./scripts/enterprise/docker_build
      - name: Upload Enterprise Image
        run: ./scripts/enterprise/docker_push
        env:
          DOCKER_USER: ${{ secrets.REPO_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.REPO_PASSWORD }}
