name: 'release_build'
on:
  push:
    branches:
      - 'release/**'

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build & Test Microservice on Release branches
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build
        run: >
          ./mvnw clean verify
          -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST
          -Dspring.rabbitmq.host=localhost
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -U -B $MAVEN_OPTS
      - name: Build Image
        run: ./scripts/docker_build_release
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
          VERSION: ${{ env.RELEASE_VERSION }}
      - name: Upload Image
        run: ./scripts/docker_push_release
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
          VERSION: ${{ env.RELEASE_VERSION }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
